project:
  type: website

website:
  title: "Steven Wolf - Data World"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: https://datawolf04.github.io/crossCountryMeetSummaries/
        text: Cross Country
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/steven-wolf-253b6625a
      - icon: github
        href: https://github.com/datawolf04/
      - icon: rss
        href: index.xml
  # Add these in when I post this so that it will generate an RSS feed
  site-url: https://datawolf04.github.io
  description: "A place to play with data"

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    toc-location: right
    
execute: 
  freeze: auto



